version: 0.2

phases:
  install:
    commands:
      - echo "No install needed"
build:
  commands:
    - echo "Copying files to S3..."
    - aws s3 sync . s3://find-me-2.2 --delete --exact-timestamps

artifacts:
  files:
    - '**/*'
