phases:
install:
runtime-versions:
nodejs: 18
commands:
- echo "Installing dependencies..."
build:
commands:
- echo "Building project..."
# Add your build steps here (example: npm run build)
post_build:
commands:
- echo "Deploying only changed files to S3..."
# Sync without deleting, only upload new/modified files
- aws s3 sync ./dist s3://YOUR_BUCKET_NAME --exact-timestamps
artifacts:
files:
- '**/*'
