version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
   commands:
     - echo "Installing dependencies if any"

build:
  commands:
  - echo "Building and deploying static website..."
  - aws s3 sync "src/" "s3://find-me-2.1" --delete
  - aws cloudfront create-invalidation --distribution-id "E53TEA4J2CIO0" --paths "/*"

artifacts:
  files:
    - '**/*'
