version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies needed for static website."

build:
  commands:
  - echo "Deploying portfolio website to S3..."
  # Sync only changed files (fast deployment, no unnecessary deletes)
  - aws s3 sync src/ s3://find-me-2.2/ --exact-timestamps --delete

  # Invalidate CloudFront so updates show immediately
  - aws cloudfront create-invalidation --distribution-id E53TEA4J2CIO0 --paths "/*"

artifacts:
  files: []
