version: 0.2

phases:
  install:
    runtime-versions:
       nodejs: 18
commands:
- echo "Installing dependencies if any"

build:
  commands:
  - echo "Deploying static website with correct metadata..."
      - aws s3 cp src/ s3://find-me-2.1/ --recursive --exclude "*" --include "*.html" --content-type "text/html"
      - aws s3 cp src/ s3://find-me-2.1/ --recursive --exclude "*" --include "*.css" --content-type "text/css"
      - aws s3 cp src/ s3://find-me-2.1/ --recursive --exclude "*" --include "*.js" --content-type "application/javascript"
      - aws s3 cp src/ s3://find-me-2.1/ --recursive --exclude "*" --include "*.png" --content-type "image/png"
      - aws s3 cp src/ s3://find-me-2.1/ --recursive --exclude "*" --include "*.jpg" --content-type "image/jpeg"
      - aws s3 cp src/ s3://find-me-2.1/ --recursive --exclude "*" --include "*.jpeg" --content-type "image/jpeg"
      - aws s3 cp src/ s3://find-me-2.1/ --recursive --exclude "*" --include "*.svg" --content-type "image/svg+xml"
      - aws s3 cp src/ s3://find-me-2.1/ --recursive --exclude "*" --include "*.ttf" --content-type "font/ttf"
   - echo   "Cleaning dist folder..."
   - rm -rf dist
   - mkdir -p dist
   - echo "copying source files to dist..."
   - cp -r scr/* dist/
   - echo "Deploying to s3..."
   - echo "Building and deploying static website..."
   - aws s3 sync "src/" "s3://find-me-2.1" --delete
   - aws cloudfront create-invalidation --distribution-id "E53TEA4J2CIO0" --paths "/*"

artifacts:
  files:
    - '**/*'
