version: 0.2

phases:
  install:

    commands:
      - echo "No dependencies needed for static website."
      
build:
  commands:
  - echo "Starting build..."
  # Sync contents of scr/ to S3 root
  - aws s3 sync scr/ s3://find-me-2.1 --exact-timestamps
  # Ensure metadata is correct
  - aws s3 cp s3://find-me-2.1 s3://find-me-2.2 --recursive --exclude "*" --include "*.html" --content-type "text/html" --metadata-directive REPLACE
  - aws s3 cp s3://find-me-2.1 s3://find-me-2.2 --recursive --exclude "*" --include "*.css" --content-type "text/css" --metadata-directive REPLACE
  - aws s3 cp s3://find-me-2.1 s3://find-me-2.2 --recursive --exclude "*" --include "*.js" --content-type "application/javascript" --metadata-directive REPLACE
  - aws s3 cp s3://find-me-2.1 s3://find-me-2.2 --recursive --exclude "*" --include "*.png" --include "*.jpg" --include "*.jpeg" --include "*.gif" --include "*.svg" --content-type "image/*" --metadata-directive REPLACE
  # Invalidate CloudFront cache so changes are visible immediately
  - aws cloudfront create-invalidation --distribution-id E53TEA4J2CIO0 --paths "/*"

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build
  secondary-artifacts:
    myBucket:
      files:
        - '**/*'
      name: myArtifact
      override-artifact-name: true
      packging: zip
      
